Repository toge-dog/backend, pull requests merged in 2024-08, with the labels that each got.

#51 fix:#46 매칭 mapping & Repository method 오류 수정
  src/main/java/com/togedog/match/controller/MatchController.java
  src/main/java/com/togedog/match/repository/MatchRepository.java
  src/main/java/com/togedog/match/service/MatchService.java
Labels: bug

#53 feat:#52 Security 권한 부여 기능 구현
  build.gradle
  src/main/java/com/togedog/auth/dto/LoginDto.java
  src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/togedog/auth/filter/JwtVerificationFilter.java
  src/main/java/com/togedog/auth/jwt/JwtTokenizer.java
  src/main/java/com/togedog/auth/userdetails/MemberDetailsService.java
  src/main/java/com/togedog/auth/utils/CustomAuthorityUtils.java
  src/main/java/com/togedog/config/SecurityConfiguration.java
  src/main/java/com/togedog/member/member/Member.java
  src/main/java/com/togedog/member/service/MemberService.java
Labels: enhancement

#69 fix:#68 Matching - Member 연관 관계 설정
  src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/togedog/auth/userdetails/MemberDetailsService.java
  src/main/java/com/togedog/match/dto/MatchDto.java
  src/main/java/com/togedog/match/mapper/MatchMapper.java
  src/main/java/com/togedog/match/repository/MatchRepository.java
  src/main/java/com/togedog/matching/controller/MatchingController.java
  src/main/java/com/togedog/matching/dto/MatchingDto.java
  src/main/java/com/togedog/matching/entity/Matching.java
  src/main/java/com/togedog/matching/mapper/MatchingMapper.java
  src/main/java/com/togedog/matching/repository/MatchingRepository.java
  src/main/java/com/togedog/matching/service/MatchingService.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/member/service/MemberService.java
Labels: bug, enhancement

#74 feat:#72 반려동물entity/dto구현
  src/main/java/com/togedog/friend/controller/FriendController.java
  src/main/java/com/togedog/friend/mapper/FriendMapper.java
  src/main/java/com/togedog/friend/service/FriendService.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/pet/dto/PetDto.java
  src/main/java/com/togedog/pet/entity/Pet.java
Labels: enhancement

#75 feat:#11 JWT 발행 기능
  src/main/java/com/togedog/auth/dto/LoginDto.java
  src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/togedog/auth/filter/JwtVerificationFilter.java
  src/main/java/com/togedog/auth/handler/MemberAccessDeniedHandler.java
  src/main/java/com/togedog/auth/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/togedog/auth/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/togedog/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/togedog/auth/utils/ErrorResponder.java
  src/main/java/com/togedog/board/repository/BoardRepository.java
  src/main/java/com/togedog/config/SecurityConfiguration.java
  src/main/java/com/togedog/errorResponse/ErrorResponse.java
Labels: enhancement

#79 fix:#46 matching restapi변경
  src/main/java/com/togedog/audit/Auditable.java
  src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/togedog/exception/ExceptionCode.java
  src/main/java/com/togedog/matching/controller/MatchingController.java
  src/main/java/com/togedog/matching/dto/MatchingDto.java
  src/main/java/com/togedog/matching/entity/Matching.java
  src/main/java/com/togedog/matching/mapper/MatchingMapper.java
  src/main/java/com/togedog/matching/repository/MatchingRepository.java
  src/main/java/com/togedog/matching/service/MatchingService.java
Labels: bug

#86 Feat/pets
  src/main/java/com/togedog/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/togedog/config/SecurityConfiguration.java
  src/main/java/com/togedog/exception/ExceptionCode.java
  src/main/java/com/togedog/friend/dto/Dto.java
  src/main/java/com/togedog/friend/entity/Friend.java
  src/main/java/com/togedog/friend/repository/FriendRepository.java
  src/main/java/com/togedog/friend/service/FriendService.java
  src/main/java/com/togedog/member/controller/MemberController.java
  src/main/java/com/togedog/member/dto/MemberDto.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/member/mapper/MemberMapper.java
  src/main/java/com/togedog/member/repository/MemberRepository.java
  src/main/java/com/togedog/member/service/MemberService.java
  src/main/java/com/togedog/pet/controller/PetController.java
  src/main/java/com/togedog/pet/dto/PetDto.java
  src/main/java/com/togedog/pet/entity/Pet.java
  src/main/java/com/togedog/pet/mapper/PetMapper.java
  src/main/java/com/togedog/pet/repository/PetRepository.java
  src/main/java/com/togedog/pet/service/PetService.java
Labels: enhancement

#90 feat:#89 matchingStandBy 구현
  src/main/java/com/togedog/config/SecurityConfiguration.java
  src/main/java/com/togedog/exception/ExceptionCode.java
  src/main/java/com/togedog/matching/controller/MatchingController.java
  src/main/java/com/togedog/matching/dto/MatchingDto.java
  src/main/java/com/togedog/matching/entity/Matching.java
  src/main/java/com/togedog/matching/mapper/MatchingMapper.java
  src/main/java/com/togedog/matching/service/MatchingService.java
  src/main/java/com/togedog/matchingStandBy/controller/MatchingStandByController.java
  src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java
  src/main/java/com/togedog/matchingStandBy/entity/MatchingStandBy.java
  src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java
  src/main/java/com/togedog/matchingStandBy/repository/MatchingStandByRepository.java
  src/main/java/com/togedog/matchingStandBy/service/MatchingStandByService.java
  src/main/java/com/togedog/member/entity/Member.java
Labels: enhancement

#91 fix:#89 mapper 연관관계 오류 수정
  src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java
  src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java
Labels: bug

#94 fix:#52 Cors config 수정
  src/main/java/com/togedog/config/SecurityConfiguration.java
Labels: bug

#95 fix:#89 Post Dto 누락 수정
  src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java
Labels: bug

#126 feat:#115, #114, #113, #112, #118, #123, #124, #54, #83
  src/main/java/com/togedog/auth/controller/AuthController.java
  src/main/java/com/togedog/auth/dto/RedisProperties.java
  src/main/java/com/togedog/auth/service/AuthService.java
  src/main/java/com/togedog/email/config/EmailConfig.java
  src/main/java/com/togedog/email/config/RedisConfig.java
  src/main/java/com/togedog/email/service/EmailVerificationService.java
  src/main/java/com/togedog/email/tool/EmailTool.java
  src/main/java/com/togedog/email/tool/RedisTool.java
  src/main/java/com/togedog/member/dto/VerificationRequest.java
  src/main/resources/application-mail.yml
  src/main/resources/templates/hello-oauth2.html
Labels: bug, enhancement

#130 feat:#115, #114, #113, #112, #118, #123, #124, #54, #83 기능구현
  Dockerfile
  build.gradle
  src/main/java/com/togedog/TogeDogApplication.java
  src/main/java/com/togedog/auth/controller/AuthController.java
  src/main/java/com/togedog/auth/dto/RedisProperties.java
  src/main/java/com/togedog/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/togedog/auth/filter/JwtVerificationFilter.java
  src/main/java/com/togedog/auth/jwt/JwtTokenizer.java
  src/main/java/com/togedog/auth/service/AuthService.java
  src/main/java/com/togedog/config/SecurityConfiguration.java
  src/main/java/com/togedog/email/config/EmailConfig.java
  src/main/java/com/togedog/email/config/RedisConfig.java
  src/main/java/com/togedog/email/service/EmailVerificationService.java
  src/main/java/com/togedog/email/tool/EmailTool.java
  src/main/java/com/togedog/email/tool/RedisTool.java
  src/main/java/com/togedog/exception/ExceptionCode.java
  src/main/java/com/togedog/friend/controller/FriendController.java
  src/main/java/com/togedog/friend/dto/Dto.java
  src/main/java/com/togedog/friend/mapper/FriendMapper.java
  src/main/java/com/togedog/friend/repository/FriendRepository.java
  src/main/java/com/togedog/friend/service/FriendService.java
  src/main/java/com/togedog/member/controller/MemberController.java
  src/main/java/com/togedog/member/dto/MemberDto.java
  src/main/java/com/togedog/member/dto/VerificationRequest.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/member/repository/MemberRepository.java
  src/main/java/com/togedog/member/service/MemberService.java
  src/main/java/com/togedog/pet/controller/PetController.java
  src/main/java/com/togedog/pet/dto/PetDto.java
  src/main/java/com/togedog/pet/repository/PetRepository.java
  src/main/java/com/togedog/pet/service/PetService.java
  src/main/java/com/togedog/redis/config/RedisConfig.java
  src/main/java/com/togedog/redis/tool/RedisTool.java
  src/main/resources/application-mail.yml
  src/main/resources/templates/hello-oauth2.html
Labels: bug, enhancement

#134 Feat/sse
  src/main/java/com/togedog/auth/service/AuthService.java
  src/main/java/com/togedog/board/dto/BoardDto.java
  src/main/java/com/togedog/member/controller/MemberController.java
  src/main/java/com/togedog/member/dto/MemberDto.java
  src/main/java/com/togedog/member/dto/VerificationRequest.java
  src/main/java/com/togedog/member/mapper/MemberMapper.java
  src/main/java/com/togedog/member/repository/MemberRepository.java
  src/main/java/com/togedog/member/service/MemberService.java
Labels: enhancement

#137 feat:#34 chatRoom 구현
  src/main/java/com/togedog/chatRoom/controller/ChatRoomController.java
  src/main/java/com/togedog/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/togedog/chatRoom/entity/ChatRoom.java
  src/main/java/com/togedog/chatRoom/entity/ChatRoomMember.java
  src/main/java/com/togedog/chatRoom/mapper/ChatRoomMapper.java
  src/main/java/com/togedog/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/togedog/chatRoom/service/ChatRoomService.java
  src/main/java/com/togedog/eventListener/EventCaseEnum.java
  src/main/java/com/togedog/eventListener/ServiceEventListener.java
  src/main/java/com/togedog/matchingStandBy/service/MatchingStandByService.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/member/repository/MemberRepository.java
  src/main/java/com/togedog/member/service/MemberService.java
Labels: enhancement

#139 feat:#138 chat package 추가
  build.gradle
  src/main/java/com/togedog/chat/config/WebSocketConfig.java
  src/main/java/com/togedog/chat/controller/ChatController.java
  src/main/java/com/togedog/chat/dto/ChatMessageDto.java
  src/main/java/com/togedog/chat/entity/ChatMessage.java
  src/main/java/com/togedog/chat/service/ChatService.java
  src/main/java/com/togedog/chatRoom/controller/ChatRoomController.java
  src/main/java/com/togedog/chatRoom/repository/ChatRoomMemberRepository.java
  src/main/java/com/togedog/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/togedog/config/SecurityConfiguration.java
Labels: enhancement

#140 fix:#33 matching create 중복에 대한 처리 방식 변경
  src/main/java/com/togedog/email/service/EmailVerificationService.java
  src/main/java/com/togedog/matching/service/MatchingService.java
Labels: enhancement

#147 feat:#138 채팅 검증 및 sub pub 구현
  src/main/java/com/togedog/chat/config/WebSocketConfig.java
  src/main/java/com/togedog/chat/controller/ChatController.java
  src/main/java/com/togedog/chat/dto/ChatDto.java
  src/main/java/com/togedog/chat/dto/ChatMessageDto.java
  src/main/java/com/togedog/chat/entity/Chat.java
  src/main/java/com/togedog/chat/entity/ChatMessage.java
  src/main/java/com/togedog/chat/handler/StompHandler.java
  src/main/java/com/togedog/chat/mapper/ChatMapper.java
  src/main/java/com/togedog/chat/repository/ChatRepository.java
  src/main/java/com/togedog/chat/service/ChatService.java
  src/main/java/com/togedog/chatRoom/entity/ChatRoom.java
  src/main/java/com/togedog/chatRoom/entity/ChatRoomMember.java
  src/main/java/com/togedog/chatRoom/repository/ChatRoomMemberRepository.java
Labels: enhancement

#148 fix:#46 matching get 동작 방식 수정
  src/main/java/com/togedog/auth/jwt/JwtTokenizer.java
  src/main/java/com/togedog/exception/ExceptionCode.java
  src/main/java/com/togedog/matching/entity/Matching.java
  src/main/java/com/togedog/scheduler/TimeCheckScheduler.java
Labels: bug, enhancement

#151 feat:#150, #149 게시판 CRUD 수정, 아이디찾기 기능, 회원가입Api 분리
  src/main/java/com/togedog/board/controller/BoardController.java
  src/main/java/com/togedog/board/dto/BoardDto.java
  src/main/java/com/togedog/board/entity/Board.java
  src/main/java/com/togedog/board/entity/BoardAnnouncement.java
  src/main/java/com/togedog/board/entity/BoardInquiry.java
  src/main/java/com/togedog/board/mapper/BoardMapper.java
  src/main/java/com/togedog/board/repository/BoardRepository.java
  src/main/java/com/togedog/board/service/BoardService.java
  src/main/java/com/togedog/friend/controller/FriendController.java
  src/main/java/com/togedog/member/controller/MemberController.java
  src/main/java/com/togedog/member/dto/MemberDto.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/member/mapper/MemberMapper.java
  src/main/java/com/togedog/member/repository/MemberRepository.java
  src/main/java/com/togedog/member/service/MemberService.java
Labels: bug, enhancement

#152 fix
  src/main/java/com/togedog/audit/Auditable.java
  src/main/java/com/togedog/member/entity/Member.java
  src/main/java/com/togedog/member/repository/MemberRepository.java
  src/main/java/com/togedog/member/service/MemberService.java
Labels: bug

#153 feat:#138 채팅 조회 기능 구현
  src/main/java/com/togedog/chat/entity/Chat.java
  src/main/java/com/togedog/chat/mapper/ChatMapper.java
  src/main/java/com/togedog/chat/repository/ChatRepository.java
  src/main/java/com/togedog/chatRoom/controller/ChatRoomController.java
  src/main/java/com/togedog/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/togedog/chatRoom/mapper/ChatRoomMapper.java
  src/main/java/com/togedog/chatRoom/repository/ChatRoomMemberRepository.java
  src/main/java/com/togedog/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/togedog/chatRoom/service/ChatRoomService.java
  src/main/java/com/togedog/dto/MultiResponseDto.java
  src/main/java/com/togedog/matching/controller/MatchingController.java
  src/main/java/com/togedog/matching/repository/MatchingRepository.java
  src/main/java/com/togedog/matching/service/MatchingService.java
Labels: bug, enhancement

#160 feat:#46 matching - marker 연결관계 설정
  src/main/java/com/togedog/eventListener/EventCaseEnum.java
  src/main/java/com/togedog/eventListener/ServiceEventListener.java
  src/main/java/com/togedog/matching/service/MatchingService.java
  src/main/java/com/togedog/member/controller/MemberController.java
  src/main/java/com/togedog/redis/MarkerService.java
Labels: enhancement

#161 Feat/map
  src/main/java/com/togedog/email/config/EmailConfig.java
  src/main/java/com/togedog/email/config/RedisConfig.java
  src/main/java/com/togedog/email/service/EmailVerificationService.java
  src/main/java/com/togedog/email/tool/RedisTool.java
  src/main/java/com/togedog/matching/repository/MatchingRepository.java
  src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java
  src/main/java/com/togedog/matchingStandBy/repository/MatchingStandByRepository.java
  src/main/resources/application-mail.yml
Labels: bug

#164 feat:#46 matching - marker 회원 조회 기능 구현
  src/main/java/com/togedog/matching/controller/MatchingController.java
  src/main/java/com/togedog/matching/dto/MatchingDto.java
  src/main/java/com/togedog/matching/mapper/MatchingMapper.java
  src/main/java/com/togedog/matching/repository/MatchingRepository.java
  src/main/java/com/togedog/matching/service/MatchingService.java
Labels: bug, enhancement

#165 fix:#46 matching 현황 조회 기능 오류 수정
  src/main/java/com/togedog/matching/controller/MatchingController.java
  src/main/java/com/togedog/matching/entity/Matching.java
  src/main/java/com/togedog/matching/mapper/MatchingMapper.java
  src/main/java/com/togedog/matching/repository/MatchingRepository.java
  src/main/java/com/togedog/matching/service/MatchingService.java
  src/main/java/com/togedog/matchingStandBy/dto/MatchingStandByDto.java
  src/main/java/com/togedog/matchingStandBy/entity/MatchingStandBy.java
  src/main/java/com/togedog/matchingStandBy/mapper/MatchingStandByMapper.java
  src/main/java/com/togedog/matchingStandBy/repository/MatchingStandByRepository.java
Labels: bug, enhancement

#167 feat:#166 Boardtype 관련 Board패키지 수정
  src/main/java/com/togedog/board/controller/BoardController.java
  src/main/java/com/togedog/board/dto/BoardDto.java
  src/main/java/com/togedog/board/mapper/BoardMapper.java
  src/main/java/com/togedog/board/service/BoardService.java
  src/main/java/com/togedog/comment/entity/Comment.java
Labels: enhancement

#169 fix:168 BoardMapper, BoardDto 수정
  src/main/java/com/togedog/audit/Auditable.java
  src/main/java/com/togedog/board/dto/BoardDto.java
  src/main/java/com/togedog/board/mapper/BoardMapper.java
Labels: enhancement
